/* SAFE — News rotation */
(function(){
  'use strict';

  var items = [
    { date:'Tuesday, June 16 2026', region:'Vale of White Horse, UK', category:'Local Government & Families', emoji:'🏛️', title:'Streamlined Framework Announced to Better Serve Local Families', desc:'The Vale of White Horse District Council detailed structural updates regarding a sweeping local government reorganisation. The initiative aims to combine multiple district resources into unified unitary frameworks to eliminate bureaucratic duplication. This ensures that essential family services — ranging from adult social care and highways to SEND (special educational needs and disabilities) support — are managed seamlessly under a single, easily accessible roof for residents.', link:'https://www.whitehorsedc.gov.uk', linkLabel:'Read' },
    { date:'Monday, June 15 2026', region:'UK', category:'Youth Employment', emoji:'💼', title:'Major £2.5 Billion Investment Confirms 180 New Youth Employment Hubs', desc:'The Department for Work and Pensions officially confirmed the exact locations for nearly 180 brand-new Youth Hubs across Great Britain. Operating out of local sports clubs, libraries, and community venues, these hubs form part of a massive national expansion designed to ensure young people are never more than an hour away from wrap-around help. The centres will offer tailored career coaching directly alongside localised housing advice and mental health support.', link:'https://www.gov.uk/dwp', linkLabel:'Read' },
    { date:'Monday, June 15 2026', region:'Newcastle-under-Lyme, UK', category:'Community Funding', emoji:'🧸', title:'Grassroots Community Fund Launched for Nurseries and Playgroups', desc:'The Newcastle-under-Lyme Borough Council introduced a proactive new Community Fund. By reprioritising existing civic growth budgets, the fund allocates a dedicated annual resource of £2,500 to every single local councillor. This allows representatives to immediately back local volunteers and fast-track one-off neighbourhood projects, such as buying new toys for playgroups, updating nursery equipment, or financing social outings for older residents.', link:'https://www.newcastle-staffs.gov.uk', linkLabel:'Read' },
    { date:'Monday, June 15 2026', region:'Stroud, UK', category:'Cost of Living', emoji:'🤝', title:'Stroud Allocates £227,000 to Fight Cost-of-Living Pressures', desc:'During key council chamber sessions, Stroud District Council leadership approved the direct allocation of £227,000 toward local cost-of-living relief. Distributed via the area\'s trusted Community Hubs Network — including local foodbanks and Citizens Advice branches — the localised funding is aimed directly at supporting vulnerable households managing immediate strain from essential grocery and utility bills.', link:'https://www.stroud.gov.uk', linkLabel:'Read' },
    { date:'Monday, June 15 2026', region:'Taipei, Taiwan', category:'Youth Solidarity', emoji:'🌍', title:'Global Youth Build Cross-Cultural Bonds at World Health Summit', desc:'At the international Rotary Convention in Taipei, Taiwan, young attendees and community organisers gathered for a landmark global breakthrough session. While world leaders highlighted accelerating milestones toward a completely polio-free world, young delegates focused on building personal solidarity networks, exchanging ideas on combatting cyberbullying, and trading handmade friendship bracelets on the convention floor.', link:'https://www.rotary.org', linkLabel:'Read' },
    { date:'Sunday, June 14 2026', region:'Global', category:'Youth Mental Health', emoji:'📚', title:'Peer Mentorship Networks Launch to Help Teens Combat Burnout', desc:'In response to rising academic stress and digital fatigue, youth organisations and peer ministries kicked off an early-summer mental wellness campaign. The specialised devotions and workshops focus on helping secondary-school students dismantle the anxiety of social media metric-chasing, reminding young participants of their intrinsic human worth separate from grades, popularity, or internet followers.', link:'https://www.youngminds.org.uk', linkLabel:'Read' },
    { date:'Saturday, June 13 2026', region:'Budapest, Hungary', category:'LGBTQ+ Rights', emoji:'🏳️\u200d🌈', title:'Major Inclusion Victory Headlines Weekly Global Good News', desc:'In a major milestone for human rights, local authorities officially approved the Budapest Pride Parade, fully reversing a previously contested ban. The achievement headlined a global week of positive news, which also featured an independent family in Tasmania using their maritime engineering expertise to construct the world\'s largest zero-emission, 40-megawatt-hour battery-electric cargo and service vessel.', link:'https://www.positive.news', linkLabel:'Read' },
    { date:'Saturday, June 13 2026', region:'Isle of Man, UK', category:'Wildlife Conservation', emoji:'🪶', title:'Custom Decoys Successfully Coax Endangered Puffins to Safe New Colonies', desc:'British conservation scientists announced a creative wildlife victory on the Isle of Man. Knowing that puffins are highly social birds that refuse to nest unless surrounded by a busy crowd, researchers deployed dozens of realistic, custom-crafted "decoy" puffins along the coast. The experiment has proven a massive hit, successfully convincing real passing puffins to drop down and confidently establish brand-new nesting colonies.', link:'https://www.rspb.org.uk', linkLabel:'Read' },
    { date:'Friday, June 12 2026', region:'California, USA', category:'Wildlife Infrastructure', emoji:'🦌', title:'New California Wildlife Overpass Welcomes First Animal Guests Ahead of Schedule', desc:'Environmentalists celebrated an unexpected success story as a massive new wildlife bridge nearing completion over a 10-lane California highway recorded its first visitors far ahead of schedule. Motion-triggered cameras caught three wild mule deer confidently exploring and navigating the heavily vegetated crossing, proving the bridge\'s immediate effectiveness at keeping local wildlife safely away from high-speed freeway traffic.', link:'https://www.ca.gov', linkLabel:'Read' },
    { date:'Thursday, May 29 2026', region:'UK', category:'Employment', emoji:'💼', title:'Employment Lifeline: 300,000 Placements for UK Youth', desc:'The UK Government announced a massive acceleration of its Youth Guarantee today, creating 300,000 new work experience and training placements across key sectors like construction, healthcare, and hospitality. Backed by a £2.5 billion support package, the initiative is designed to give young people the hands-on skills, mentorship, and confidence they need to kickstart successful careers.', link:'https://www.gov.uk', linkLabel:'Read' },
    { date:'Wednesday, May 29 2026', region:'UK', category:'Environment', emoji:'🚴', title:'England Unveils First Ever Dutch-Style "Cycle Street"', desc:'In a fantastic win for green neighborhoods and young cyclists, England officially unveiled its very first Dutch-style "cycle street" this week. This innovative urban transit design gives bicycles absolute priority over cars, creating a much safer, eco-friendly environment for children and families to actively commute.', link:'https://www.positivenews.org.uk', linkLabel:'Read' },
    { date:'Wednesday, May 29 2026', region:'Global', category:'Music & Brain', emoji:'🎵', title:'Learning an Instrument Proven as a Shield Against Digital Distraction', desc:'A fascinating study published by Spain\'s Mind, Brain, and Behaviour Research Centre revealed that formal music training significantly boosts attention spans and cognitive function in young people. Researchers found that learning an instrument trains the brain to embrace and enjoy effort, helping kids naturally resist the attention-hijacking pulls of modern social media algorithms.', link:'https://www.positivenews.org.uk', linkLabel:'Read' },
    { date:'Wednesday, May 29 2026', region:'Global', category:'Family', emoji:'👨‍👧‍👦', title:'A Generational Shift: Dads Spending More Time at Home', desc:'Fresh research based on the American Time Use Survey highlighted an incredibly positive shift in modern family dynamics. Since the pandemic, fathers have been cutting back on paid work hours to intentionally prioritize childcare, housework, and quality bonding time with their kids—marking a major generational trend toward shared parental responsibilities.', link:'https://www.positivenews.org.uk', linkLabel:'Read' },
    { date:'Wednesday, May 29 2026', region:'UK', category:'Community & Wellness', emoji:'🧘', title:'Bradford Mosque\'s Over-50s Fitness Class Goes Viral', desc:'Proving that community wellness crosses all generations, a video of a men\'s over-50s Pilates class hosted at the Jamia Usmania Mosque in Bradford went massively viral this week, racking up over two million views on TikTok and spreading a wave of pure, lighthearted joy across the UK.', link:'https://www.positivenews.org.uk', linkLabel:'Read' },
    { date:'Wednesday, May 29 2026', region:'UK', category:'Youth & Environment', emoji:'♻️', title:'Loughborough University Students Clear 281kg of Rubbish in "SpoGomi"', desc:'Students from Loughborough University sports clubs turned environmental cleanup into a high-energy competitive sport this week. Participating in "SpoGomi" (a combination of the word "sport" and gomi, the Japanese word for litter), teams raced against the clock to collect and sort trash. The collective student effort successfully cleared a whopping 281kg of rubbish from the local town in a single afternoon.', link:'https://www.positivenews.org.uk', linkLabel:'Read' },
    { date:'Tuesday, May 28 2026', region:'UK', category:'Youth Work', emoji:'⭐', title:'Moray Youth Worker Nominated for Top National Award', desc:'Alison Smith, a dedicated youth worker at Milne\'s High School in Moray, Scotland, has been shortlisted for Youth Worker of the Year at the National Youth Work Awards. Nominated in secret by her proud colleagues, Alison was celebrated for her incredible work with disengaged students, helping them rebuild their self-confidence, improve school attendance, and successfully transition into college or career paths.', link:'https://www.moray.gov.uk', linkLabel:'Read' },
    { date:'Sunday, May 26 2026', region:'USA', category:'Arts & Youth', emoji:'🎨', title:'Airport Art Competition Celebrates Talented High Schoolers', desc:'The 19th Annual High School Visual Arts Competition wrapped up this week at Memphis International Airport. The event showcased incredible submissions from local teenagers, providing up-and-coming young artists with a massive public platform to display their creative talents to thousands of global travelers.', link:'https://www.memphischamber.com', linkLabel:'Read' },
    { date:'Sunday, May 26 2026', region:'USA', category:'Sports & Adventure', emoji:'🧗', title:'Young Climbers\' Inspiring Journey Nominated for a Sports Emmy', desc:'A moving documentary following a young rock climbing team from a local nonprofit gym, Memphis Rox, has just been nominated for a Sports Emmy. The film highlights the youth team\'s life-changing expedition to Kenya to climb the continent\'s second-highest peak, beautifully demonstrating how community-focused youth sports programs can broaden horizons and transform lives.', link:'https://www.memphischamber.com', linkLabel:'Read' },
    { date:'May 25 2026', region:'UK', category:'Youth Fashion', emoji:'👗', title:'"Dopamine Dressing" Trend Empowers Youth Confidence', desc:'Wrapping up the long weekend, a new fashion report highlighted the massive rise of "dopamine dressing" among Gen Z and young adults across the UK. Instead of following rigid trends, young people are increasingly choosing to wear bright, highly individualized, and joyful clothing specifically to boost their mental health and self-expression, actively pushing back against traditional fashion anxieties.', link:'https://www.bbc.com/news', linkLabel:'Read' },
    { date:'May 24 2026', region:'Global', category:'Environment', emoji:'🌙', title:'NASA Maps Reveal Light Pollution is Actually Decreasing', desc:'In an incredibly rare and positive environmental update, NASA\'s Black Marble project shared newly analysed satellite maps showing that global efforts to curb light pollution are working. Thanks to community-led "dark sky" initiatives, several regions around the world are seeing a measurable decrease in light pollution, which is vital for the health of nocturnal wildlife and migrating birds.', link:'https://www.nasa.gov', linkLabel:'Read' },
    { date:'May 23 2026', region:'Global', category:'Marine Conservation', emoji:'🐋', title:'A Mini "Baby Boom" for Endangered Whales', desc:'Marine biologists celebrated a joyous milestone this weekend for the critically endangered North Atlantic right whale. Conservationists confirmed that a remarkable 23 new calves were born this season, offering a massive beacon of hope for the survival and recovery of the species.', link:'https://www.fisheries.noaa.gov', linkLabel:'Read' },
    { date:'May 23 2026', region:'UK', category:'Conservation', emoji:'🐧', title:'Record-Breaking Puffin Season in Wales', desc:'Nature lovers received fantastic news today! The Wildlife Trust of South and West Wales announced that puffins are having a record-breaking breeding year on Skomer Island. Volunteers doing boots-on-the-ground research recorded phenomenal numbers, proving that local marine conservation efforts are paying off.', link:'https://www.welshwildlife.org', linkLabel:'Read' },
    { date:'May 23 2026', region:'USA', category:'Youth Action', emoji:'🦅', title:'Elementary Students Help Raise $10 Million to Save Eagle Habitat', desc:'When elementary students in Danville, California, learned that a wildlife area housing a viral pair of bald eagles (Jackie and Shadow) was at risk of being developed, they leaped into action. The kids launched a massive grassroots campaign—writing letters, picking up leaves, washing cars, and posting flyers. Their efforts helped a local nonprofit cross the $2.6 million mark this weekend, well on their way to purchasing and permanently protecting the land.', link:'https://www.audubon.org', linkLabel:'Read' },
    { date:'May 22 2026', region:'Africa', category:'Conservation', emoji:'🐘', title:'Elephants Return to Eastern Zambia After 50 Years', desc:'Absent from eastern Zambia for more than half a century, elephants have officially crossed back over from neighbouring Malawi! Local youth and community response teams are now learning to safely live alongside their returning neighbours by building elephant-proof grain stores and tracking the herds via satellite collars.', link:'https://www.wildlife.org.zm', linkLabel:'Read' },
    { date:'May 22 2026', region:'Brazil', category:'Environment', emoji:'🌳', title:'Brazil\'s Atlantic Forest Deforestation Hits a 40-Year Low', desc:'In a monumental victory for global environmental advocates, data released today revealed that deforestation in Brazil\'s Atlantic Forest dropped by a staggering 40% over the last year. It is now at its lowest level since monitoring began in 1985, proving that grassroots conservation and strict protections are actively healing the planet.', link:'https://www.inpe.gov.br', linkLabel:'Read' },
    { date:'May 22 2026', region:'UK', category:'Youth Achievement', emoji:'🏆', title:'Youth Celebrate at Buckingham Palace for Gold DofE Awards', desc:'Over 300 young people from Hertfordshire alone (and thousands across the UK) gathered at Buckingham Palace to celebrate achieving their Duke of Edinburgh\'s Gold Awards. The massive celebration honoured the intense determination, community volunteering, and life skills these young people have developed. Youth Ambassador Evie delivered a powerful speech on how the programme helped her find her voice and overcome disabilities.', link:'https://www.dofe.org', linkLabel:'Read' },
    { date:'May 21 2026', region:'Global', category:'Innovation', emoji:'🧲', title:'Youth-Driven "Magnetic Surfboard" Shortlisted for Major Prize', desc:'A young team of innovators from Poland led by Przemek Ben Paczek made global headlines after their incredible invention was shortlisted for the European Inventor Award. They developed a brilliant new magnetic levitation system that can be retrofitted onto existing railways—essentially creating a clean-energy "magnetic surfboard" for freight trains that radically reduces emissions.', link:'https://www.epo.org', linkLabel:'Read' },
    { date:'May 21 2026', region:'UK', category:'Youth Independence', emoji:'🚌', title:'Free Summer Bus Travel for UK Kids', desc:'In a massive win for families and youth independence, it was officially confirmed today that a new government scheme will provide unlimited free bus travel for every child aged 5 to 15 across England throughout the upcoming August holidays. The initiative is designed to help kids easily access local community centres, parks, and summer jobs without financial barriers.', link:'https://www.gov.uk/transport', linkLabel:'Read' },
    { date:'May 20 2026', region:'UK', category:'Youth Work', emoji:'⭐', title:'Moray Youth Worker Shortlisted for Saving Students\' Futures', desc:'Alison Smith, a youth worker at Milne\'s High School in Moray, Scotland, was officially shortlisted for the prestigious National Youth Work Awards. She was nominated by her colleagues for her incredible dedication to disengaged youth. For many local teens, Alison is the sole reason they still attend school, and she successfully helped an entire group of struggling students transition into college and positive career pathways.', link:'https://www.moray.gov.uk', linkLabel:'Read' },
    { date:'May 18 2026', region:'Global', category:'Environmental Action', emoji:'🦅', title:'Students Fundraise to Save Bald Eagle Habitat', desc:'A dedicated group of students who regularly monitored a local bald eagle nest via a livestream realized the surrounding habitat was under threat of development. Leaping into action, the young environmentalists launched a massive community fundraising campaign to purchase and protect the land, ensuring the eagle chicks and future generations have a safe home.', link:'https://www.goodnewsnetwork.org', linkLabel:'Read' },
    { date:'May 17 2026', region:'Global', category:'Education', emoji:'💰', title:'Speaker Pays Off Final Year of Loans for Entire Graduating Class', desc:'In a life-changing surprise, a college commencement speaker announced from the podium that he was paying off the final year of student loans for every single graduating student in attendance. He made the massive donation in honour of his late father, instantly lifting a massive financial burden off hundreds of young adults.', link:'https://www.goodnewsnetwork.org', linkLabel:'Read' },
    { date:'May 16 2026', region:'USA', category:'Youth Recreation', emoji:'⚽', title:'New York City Launches "Soccer Streets" for Kids', desc:'Ahead of the massive 2026 World Cup arriving in the US, New York City Mayor Zohran Mamdani announced the creation of 50 car-free "soccer streets" located right next to public schools. These safe, pedestrian-only zones are hosting youth soccer clinics, art stations, and block parties to ensure every kid in the city gets to experience the joy of the game for free.', link:'https://www.goodgoodgood.co', linkLabel:'Read' },
    { date:'May 16 2026', region:'USA', category:'Youth Tribute', emoji:'👑', title:'Students Crown Hero Principal "Prom King"', desc:'In a deeply emotional tribute, high school students at Pauls Valley High School in Oklahoma decided to throw out the traditional prom court rules. Instead, they crowned their principal "Prom King" to the tune of the song "Hero," honouring him for his incredible bravery after he physically tackled a school shooter earlier in the year, protecting the student body.', link:'https://www.goodgoodgood.co', linkLabel:'Read' },
    { date:'May 16 2026', region:'Global', category:'Animal Compassion', emoji:'🤝', title:'Father-Daughter Duo Drive 600 Miles for an Animal Rescue', desc:'Showing incredible compassion, a young woman named Joanna Zelman and her father drove 600 miles across the country to rescue two male calves. Because male calves cannot produce milk, they are often discarded by the dairy industry, but this family intervened to bring the babies to an animal sanctuary where they will live out their natural lives in peace.', link:'https://www.goodgoodgood.co', linkLabel:'Read' },
    { date:'May 15 2026', region:'UK', category:'Mental Health', emoji:'💚', title:'Winterstoke Academy Turns Green for Mental Health', desc:'To actively break the stigma around teen anxiety, the entire staff at Winterstoke Hundred Academy in Weston-super-Mare united to wear green during Mental Health Awareness Week. The highly visible display of solidarity was designed to spark meaningful, open conversations with students, proving to the young people that their teachers are safe, supportive allies they can talk to about their wellbeing.', link:'https://www.cabot.ac.uk', linkLabel:'Read' },
    { date:'May 15 2026', region:'UK', category:'Democracy', emoji:'🗣️', title:'UK Youth Ambassador Shapes Europe\'s Democratic Future', desc:'The National Youth Agency (NYA) celebrated Zara Okusi, a UK Youth Ambassador who represented British young people on the European stage this week. Her powerful advocacy focused on creating formalised pathways for young people to influence major political decisions, proving that Gen Z is actively stepping up to protect and shape the democratic future of the continent.', link:'https://www.nya.org.uk', linkLabel:'Read' },
    { date:'May 15 2026', region:'Global', category:'Environmental Innovation', emoji:'🧪', title:'Teens Invent Tamarind Powder to Erase Microplastics', desc:'Three brilliant teenagers were awarded the Earth Prize for Asia after inventing an incredibly simple, natural solution to water pollution. They developed a specialized powder made from tamarind seeds that easily and safely binds to microplastics in water, allowing them to be effortlessly filtered out.', link:'https://www.goodnewsnetwork.org', linkLabel:'Read' },
    { date:'May 14 2026', region:'Global', category:'Youth Leadership', emoji:'🌍', title:'Myanmar Student Union Leads Massive Disaster Relief', desc:'A feature published today highlighted the incredible work of the Myanmar Student Union (MSU) at Tufts University. Led by student Thang Dopmul, the entirely youth-run organisation was praised for spending the last year coordinating large-scale relief efforts, hosting events, and advocating for resources to support communities devastated by the recent earthquake in Myanmar.', link:'https://tuftsdaily.com', linkLabel:'Read' },
    { date:'May 14 2026', region:'Canada', category:'Youth Resilience', emoji:'💪', title:'Children and Youth in Care Day Celebrates Resilience', desc:'Communities across Ontario, Canada, officially marked "Children and Youth in Care Day" today. Rather than focusing on systemic hardships, the day was entirely dedicated to recognising the incredible strength, resilience, and valuable contributions of young people currently or formerly navigating the child welfare system, encouraging communities to celebrate these young heroes.', link:'https://www.ontario.ca', linkLabel:'Read' },
    { date:'May 14 2026', region:'USA', category:'Community Impact', emoji:'🍋', title:'Youth Lemonade Stand Earns a \'Cincy Serves\' Honour', desc:'The Cincinnati Open announced its 2026 "Cincy Serves" honourees today, a programme dedicated to celebrating local heroes. Among those honoured with VIP stadium recognition was a young person who set up a neighbourhood lemonade stand, proving that you are never too young to start fundraising and making a tangible difference in your community.', link:'https://www.cincinnatiopentennis.com', linkLabel:'Read' },
    { date:'May 13 2026', region:'Global', category:'Youth Innovation', emoji:'🚀', title:'Young Innovators Win the \'Generation Regen Challenge\'', desc:'BMO and One Young World officially announced the winners of their inaugural Generation Regen Challenge this week. Four brilliant young innovators—Diana Virgovicova, Ranah Chavoshi, Marika Dewar-Norosky, and Emma Ekua-Bedua Hudson—were selected to receive full project funding and scholarships. Their youth-led projects are specifically focused on rebuilding and securing sustainable food systems across North America.', link:'https://www.oneyoungworld.com', linkLabel:'Read' },
    { date:'May 13 2026', region:'Europe', category:'Youth Travel', emoji:'🚆', title:'EU Proposes Radical Shift to Make Youth Train Travel Easier', desc:'In a huge win for students and young backpackers, the EU officially proposed new rules this week to end the "excessively complex" nightmare of booking cross-border trains. The new laws will force major train operators to share their data, allowing young travellers to easily plan, book, and protect their multimodal European journeys all in one place, encouraging greener travel.', link:'https://ec.europa.eu', linkLabel:'Read' },
    { date:'May 13 2026', region:'UK', category:'Youth Services', emoji:'⭐', title:'Powys Youth Service Celebrates Major Quality Award', desc:'A massive win for youth support in Wales: The Powys County Council\'s Youth Service successfully renewed its Bronze Youth Work Quality Mark. Assessors heavily praised the staff for delivering incredibly safe, inclusive, and impactful support for local young people aged 11 to 25. The best part? Young people were placed firmly at the heart of the assessment, using their voices to directly shape the service\'s future.', link:'https://www.powys.gov.uk', linkLabel:'Read' },
    { date:'May 13 2026', region:'USA', category:'Community Fundraising', emoji:'💃', title:'"Prom 2.0" Raises Funds for Local Youth', desc:'The Olympic Peninsula YMCA made the news this week for launching a brilliant and heartwarming community fundraiser called "Prom 2.0." The event invited adults to step back in time to recreate their high school prom, with every single pound raised going directly to support programmes that make a lasting, positive impact on local youth.', link:'https://www.ymca.org', linkLabel:'Read' },
    { date:'May 12 2026', region:'Bermuda', category:'Mental Health', emoji:'🧠', title:'Bermuda Launches Groundbreaking Youth Mental Health Week', desc:'Bermuda officially kicked off its Youth Mental Health Week this Tuesday. What makes this initiative so special is that it is entirely youth-led. Rather than adults lecturing teens, the week created a space for young people to guide town halls on digital wellness. The highlight? A midday "Puppy Therapy" session in Victoria Park designed to promote connection and reduce student stress.', link:'https://www.bermuda.bm', linkLabel:'Read' },
    { date:'May 12 2026', region:'USA', category:'Volunteering', emoji:'❤️', title:'Decades of Compassion for Homeless Youth Honoured', desc:'Alaska\'s First Lady announced the 2026 Volunteer Award recipients this week, and the stories were incredibly moving. Among the winners was Theresa Rodgers, who was honoured for her three decades of volunteer work at Covenant House, where she has been a steady, compassionate, and life-saving presence for vulnerable youth experiencing homelessness.', link:'https://www.covenantthouse.org', linkLabel:'Read' },
    { date:'May 01 2026', region:'Global', category:'Democracy', emoji:'📚', title:'Student Journalism Brings Hope for Democracy', desc:'University student journalists published a powerful editorial today reflecting on the anxiety of the current global political climate. Their conclusion was deeply uplifting: the passionate, truth-seeking nature of today\'s student journalists is exactly the tool needed to build a more transparent future.', link:'https://www.thebucknellian.com', linkLabel:'Read' },
    { date:'May 01 2026', region:'Global', category:'Innovation', emoji:'💡', title:'Young Winner Uses AI for Good', desc:'A brilliant young student won a major science award for using artificial intelligence to design a new molecule aimed at solving pressing global health and environmental challenges. Proof of the positive potential of next-generation technology in youth hands.', link:'https://www.globalcitizen.org', linkLabel:'Read' },
    { date:'May 01 2026', region:'Global', category:'Heroism', emoji:'🥸', title:'Middle Schoolers Turn Heroes on the School Bus', desc:'A group of quick-thinking middle school students calmly worked together to safely stop their school bus when the driver experienced a sudden medical emergency at the wheel. Their quick thinking and composure saved everyone on board.', link:'https://www.sunnyskyzsz.com', linkLabel:'Read' },
    { date:'May 01 2026', region:'Europe', category:'Youth', emoji:'🌏', title:'European Youth Week Champions "Solidarity and Fairness"', desc:'The 2026 European Youth Week wrapped up today with thousands of young people across the continent participating in civic events. The week celebrated 30 years of European youth volunteering, showcasing teenagers who have made measurable, positive differences in their local societies.', link:'https://youth.europa.eu', linkLabel:'Read' },
    { date:'May 01 2026', region:'UK', category:'Housing', emoji:'🏠', title:'Youth Organisers Celebrate Historic Renters Rights Win', desc:'The long-awaited Renters Rights Act officially took effect today in England, banning "no-fault" evictions. This monumental victory was heavily championed by youth-driven community unions like Acorn. Young organisers spent over a decade campaigning for these protections to secure stable housing for millions of young renters.', link:'https://www.positive.news', linkLabel:'Read' },
    { date:'Apr 30 2026', region:'UK', category:'Environment', emoji:'🐦', title:'The Gen Z Birdwatching Boom', desc:'A new study published by the RSPB revealed a massive 1,088% increase in 16-to-29-year-olds regularly birdwatching in Britain since 2018. Young people are using it as a way to ditch their screens, find moments of peace, and reconnect with local nature.', link:'https://www.theguardian.com', linkLabel:'Read' },
    { date:'Apr 30 2026', region:'South America', category:'Community', emoji:'🤝', title:'Teens Bridge the Generational Gap in Chile', desc:'A group of youth volunteers in Rancagua, Chile, organised a massive local effort to paint and repair 20 homes for local senior citizens. Working alongside the national programme for elderly adults, the teens spent their weekend ensuring their older neighbours felt seen, supported, and valued.', link:'https://www.churcharticles.org', linkLabel:'Read' },
    { date:'Apr 29 2026', region:'North America', category:'Environment', emoji:'🌱', title:'"Green Crew" Inspires the Next Generation', desc:'TIME for Kids highlighted 18-year-old Hannah Stockert Barisonski, who founded the "Green Crew" when she was just 13. Based in Minnesota, the youth-led group has successfully mobilised hundreds of children to actively protect their local environment, proving that you are never too young to start a conservation movement.', link:'https://www.timeforkids.com', linkLabel:'Read' },
    { date:'Apr 29 2026', region:'Global', category:'Digital', emoji:'📱', title:'Kids Teaching Kids Digital Empathy', desc:'The youth news podcast KidNuz launched a brilliant new series called "Kids Showing Kids How to Be Good Online Citizens." Instead of adults lecturing teens about screen time, the initiative empowers young people to teach their peers about digital empathy and how to navigate the internet kindly.', link:'https://www.kidnuz.org', linkLabel:'Listen' },
    { date:'Apr 28 2026', region:'UK', category:'Community', emoji:'🚘', title:'Bingley Firefighters announce "72 for the 72" community challenge', desc:'Firefighters from Bingley Fire Station are preparing a special "72 for the 72" charity challenge on May 3rd, covering 72 miles in memory of those lost at Grenfell. Opening station doors to the public, focusing on community solidarity and giving youth a chance to meet the crew.', link:'https://www.westyorksfire.gov.uk/news/bingley-firefighters-take-72-mile-challenge-ahead-grenfell-tower-anniversary', linkLabel:'Read' },
    { date:'Apr 27 2026', region:'UK', category:'Community', emoji:'🎉', title:'"One Heart, One Community" Festival - youth-led resilience project', desc:'The Youth Action Alliance in London is running a beautiful, community-driven campaign funding a free festival in June 2026 for over 2,500 residents. While honouring remembrance, the festival supports local young people, creates space for joy, and reminds residents they are valued.', link:'https://www.crowdfunder.co.uk/p/one-heart-1', linkLabel:'Read' },
    { date:'Apr 26 2026', region:'UK', category:'Health', emoji:'👀', title:'Great Ormond Street Hospital breakthrough in treating childhood blindness', desc:'Groundbreaking work treating Leber\'s congenital amaurosis (LCA), a genetic mutation causing infant blindness, is giving young people like Saffie Sandford from Hertfordshire profound improvements in their ability to see the world around them. A massive leap forward in youth healthcare.', link:'https://www.positive.news/society/good-news-stories-from-week-17-of-2026/', linkLabel:'Read' },
    { date:'Apr 25 2026', region:'Global', category:'Youth', emoji:'🚀', title:'Youth volleyball team turns tornado evacuation into joy and community', desc:'A couple\'s wedding was interrupted by tornado alarms, forcing evacuation. A youth volleyball group taking shelter in the same basement joined them, turning a scary situation into an impromptu dance party and photo session - proving young people bring joy in crisis.', link:'https://podcasts.apple.com/us/podcast/the-positive-truth-uplifting-news-positive-news/id1169234042', linkLabel:'Listen' },
    { date:'Apr 24 2026', region:'Global', category:'Climate', emoji:'🌎', title:'Goldman Environmental Prize recognises youth-led climate victories worldwide', desc:'South Korea\'s Borim Kim wins prestigious award for the first youth-led climate litigation case in Asia, proving young voices have the power to enact monumental, structural change. UK\'s Sarah Finch also honoured for her landmark legal win against big oil.', link:'https://www.positive.news/society/good-news-stories-from-week-17-of-2026/', linkLabel:'Read' },
    { date:'Apr 21 2026', region:'Global', category:'Youth Service', emoji:'🌍', title:'Global Youth Service Day - thousands mobilise this weekend', desc:'This coming weekend marks the peak of Global Youth Service Month. Thousands of young people across the UK and worldwide are registered for community service - from cleanup events to intergenerational tech cafes.', link:'https://www.ysa.org/38th-annual-global-youth-service-day-april-24-26-2026-youth-service-month', linkLabel:'Read' },
    { date:'Apr 20 2026', region:'Global', category:'Climate', emoji:'🌎', title:'"Green Nobel" winners announced - youth leading the charge', desc:'Goldman Environmental Prize 2026 highlights Borim Kim from South Korea, whose youth-led climate lawsuit forced ambitious emissions targets and inspired similar movements across Asia. Proof that young people are reshaping climate policy.', link:'https://news.mongabay.com/2026/04/meet-the-2026-goldman-environmental-prize-winners/', linkLabel:'Read' },
    { date:'Apr 18 2026', region:'Global', category:'Youth', emoji:'🌐', title:'UN ECOSOC Youth Forum: Gen Z redesigns solutions for 2030', desc:'Young leaders gathered at UN HQ for "Innovate, Unite and Transform" to showcase how Gen Z is actively building solutions for clean water, sustainable cities, and climate action.', link:'https://news.un.org/en/story/2026/04/1067972', linkLabel:'Read' },
    { date:'Apr 18 2026', region:'Global', category:'Climate', emoji:'🔥', title:'Direct funding now reaches young climate leaders under 30', desc:'UNDP and Italy launch Youth4Climate funding that bypasses bureaucracy, putting resources directly into the hands of young innovators leading local environmental projects.', link:'https://climatepromise.undp.org', linkLabel:'Read' },
    { date:'Apr 17 2026', region:'UK', category:'Environment', emoji:'🌍', title:'Sarah Finch wins landmark climate case - game-changer for youth campaigners', desc:'A UK legal precedent that has become transformative for young environmental advocates. Her victory has already been used to block new oil and coal projects, securing a cleaner future for the next generation.', link:'https://www.theguardian.com/environment/2026/apr/woman-environmental-case-goldmanprize', linkLabel:'Read' },
    { date:'Apr 16 2026', region:'UK', category:'Arts', emoji:'🎛', title:'National Youth Orchestra "Collide" series receives rave reviews', desc:'Hundreds of young musicians under conductor Alpesh Chauhan demonstrated "remarkable intensity" - proving the arts are thriving among UK youth despite economic pressures on school music programmes.', link:'https://www.theguardian.com/music/2026/apr/national-youth-orchestra-collide-review', linkLabel:'Read' },
    { date:'Apr 15 2026', region:'UK', category:'Community', emoji:'🤲', title:'Grenfell Foundation youth programmes empower next generation', desc:'The Grenfell Children and Young People\'s Fund continues multi-year support: youth workers, community projects, boxing training through Fight 4 Grenfell, and artist collaborations with survivors - rebuilding with healing and agency at the centre.', link:'https://www.grenfellfoundation.org.uk/community-projects', linkLabel:'Read' },
    { date:'Apr 15 2026', region:'UK', category:'SAFE', emoji:'✍️', title:'SAFE petition crosses its first milestone', desc:'The public mandate for the UK\'s first holistic youth development hub is building. Every signature becomes evidence of demand - data that funders, councils and partners cannot ignore.', link:'https://www.change.org/p/build-the-uk-s-first-holistic-youth-development-hub-to-transform-at-risk-lives', linkLabel:'Sign' },
    { date:'Apr 8 2026', region:'Africa', category:'Reforestation', emoji:'🌳', title:'Great Green Wall crosses 30% of Sahel target', desc:'A continent-wide effort to restore 100 million hectares of degraded land across the Sahel is now past 30% complete in participating nations, according to UNCCD updates. Jobs, food security and biodiversity moving in the right direction.', link:'https://www.unccd.int/our-work/ggwi', linkLabel:'Read' },
    { date:'Apr 1 2026', region:'Global', category:'Health', emoji:'🎫', title:'Global child mortality at record lows', desc:'UN figures show under-five child mortality has more than halved since 2000. Still too high - but the trend is unambiguous. Vaccines, clean water, maternal care and education working together.', link:'https://data.unicef.org/topic/child-survival/under-five-mortality/', linkLabel:'Read' },
    { date:'Mar 25 2026', region:'UK', category:'Youth', emoji:'🛶', title:'Record low youth reoffending in boroughs with open community hubs', desc:'Boroughs that kept youth centres open through the 2010s continue to show measurably lower reoffending rates than comparable boroughs that closed theirs. Corroborates the SAFE thesis: place matters.', link:'https://www.gov.uk/government/collections/youth-justice-statistics', linkLabel:'Read' },
    { date:'Mar 18 2026', region:'Global', category:'Energy', emoji:'🔌', title:'Renewables now account for the majority of new power capacity', desc:'The IEA reports that for the third year running, more than 80% of all new electricity capacity added globally came from renewables. Cost, not politics, is doing the work.', link:'https://www.iea.org/reports/renewables-2024', linkLabel:'Read' },
    { date:'Mar 11 2026', region:'South America', category:'Literacy', emoji:'📖', title:'Adult literacy programmes double enrolment in rural Brazil', desc:'State-run literacy and numeracy evening schools in rural Brazilian municipalities report record enrolment, particularly from women over 40 returning to formal education for the first time.', link:'https://en.unesco.org/themes/literacy', linkLabel:'Read' },
    { date:'Mar 4 2026', region:'Asia', category:'Ocean', emoji:'🌅', title:'Coral restoration at scale off the Philippines', desc:'Community-led reef restoration is producing visible regrowth on previously bleached sites. Simple design. Local labour. Patience. Works where top-down policy has not.', link:'https://www.iucn.org/our-work/topic/coral-reefs', linkLabel:'Read' },
    { date:'Feb 25 2026', region:'Europe', category:'Mental Health', emoji:'💭', title:'Peer-led youth mental health pilots outperform traditional triage', desc:'Several European pilots show that youth-peer-led early intervention produces better engagement and outcomes than adult clinician-only pathways. Young people listen to young people first.', link:'https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health', linkLabel:'Read' },
    { date:'Feb 18 2026', region:'Global', category:'Science', emoji:'💻', title:'Global polio cases at an all-time low', desc:'Wild polio remains endemic in only two countries. A disease that paralysed hundreds of thousands per year is now measured in single and double digits. Proof that coordinated, sustained effort works.', link:'https://polioeradication.org/', linkLabel:'Read' },
    { date:'Feb 11 2026', region:'Global', category:'Conservation', emoji:'🐋', title:'Humpback whale population rebounds 90% from near-extinction', desc:'From roughly 450 in the 1950s to more than 25,000 today in the Southern Hemisphere. Moratoriums work. The recovery is slow, unglamorous, and absolute.', link:'https://iwc.int/', linkLabel:'Read' },
    { date:'Feb 4 2026', region:'Kenya', category:'Education', emoji:'📚', title:'Kenyan free digital libraries reach 1 million rural learners', desc:'Solar-powered, offline-first tablet libraries now serve over a million rural students. Books in local languages, science in Swahili, no electricity required.', link:'https://www.unicef.org/education', linkLabel:'Read' },
    { date:'Jan 28 2026', region:'Global', category:'Poverty', emoji:'💵', title:'Extreme poverty rate at lowest level on record', desc:'The share of humanity living under $2.15/day continues a four-decade decline. The last mile is the hardest - concentrated in fragile states - but the direction is unambiguous.', link:'https://www.worldbank.org/en/topic/poverty', linkLabel:'Read' }
  ];

  function render(){
    var grid = document.getElementById('news-grid');
    if(!grid) return;

    var featured = items.slice(0, 9);

    grid.innerHTML = featured.map(function(it){
      var linkLabel = it.linkLabel || 'Read';
      return (
        '<article class="news-card">' +
          '<span class="news-globe">' + it.emoji + '</span>' +
          '<div class="news-meta"><span>' + it.region + '</span><span>' + it.category + '</span></div>' +
          '<span class="news-date">' + it.date + '</span>' +
          '<h3 class="news-title">' + it.title + '</h3>' +
          '<p class="news-desc">' + it.desc + '</p>' +
          '<a class="news-link" href="' + it.link + '" target="_blank" rel="noopener">' + linkLabel + ' &rarr;</a>' +
        '</article>'
      );
    }).join('');

    var banner = document.getElementById('news-week');
    if(banner){
      var now = new Date();
      var opts = { day:'numeric', month:'short', year:'numeric' };
      banner.innerHTML =
        '<span>Field Reports · Week 25</span>' +
        '<strong>What mainstream media won\'t highlight</strong>' +
        '<span style="text-align: right;"><a href="youth-stories.html" style="color: inherit; text-decoration: none; border-bottom: 1px solid rgba(255,255,255,0.5); padding-bottom: 2px; transition: border-color 0.2s;">Submit Your Story</a></span>';
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', render);
  } else {
    render();
  }
})();
