/* Regenerates prices.js — the server-authoritative price list used by the Worker
   at checkout. Run after you change any price:   node update-prices.mjs
   It reads the prices already in shop.html (data-code/data-price/data-name)
   and library.html (addBookToCart), so the HTML stays the single source you edit. */
import { readFileSync, writeFileSync } from 'node:fs';

const shop = readFileSync('shop.html', 'utf8');
const lib  = readFileSync('library.html', 'utf8');
const catalog = {};
const dupes = [];

// Shop products: keyed by data-code
const tagRe = /<button[^>]*\bclass="[^"]*add-to-cart-btn[^"]*"[^>]*>/g;
let m;
while ((m = tagRe.exec(shop)) !== null) {
  const tag = m[0];
  const code  = (tag.match(/data-code="([^"]+)"/)  || [])[1];
  const price = (tag.match(/data-price="([^"]+)"/) || [])[1];
  const name  = (tag.match(/data-name="([^"]+)"/)  || [])[1];
  if (!code || price == null) continue;
  const p = Number(price);
  if (!(p > 0)) continue;
  if (catalog[code] && catalog[code].price !== p) dupes.push(code);
  catalog[code] = { name: name || code, price: p };
}

// Books: keyed by name (book cart items have no code)
const bookRe = /addBookToCart\(\s*this\s*,\s*'([^']+)'\s*,\s*'([^']+)'/g;
while ((m = bookRe.exec(lib)) !== null) {
  const name = m[1]; const p = Number(m[2]);
  if (!(p > 0)) continue;
  catalog[name] = { name, price: p };
}

const keys = Object.keys(catalog).sort();
const body = keys.map(k => '  ' + JSON.stringify(k) + ': { name: ' + JSON.stringify(catalog[k].name) + ', price: ' + catalog[k].price + ' },').join('\n');
const out = '/* AUTO-GENERATED by update-prices.mjs — do not edit by hand.\n   Server-authoritative prices (keyed by product code, or book name). */\nexport const CATALOG = {\n' + body + '\n};\n';
writeFileSync('prices.js', out, 'utf8');
console.log('Wrote prices.js with ' + keys.length + ' products' + (dupes.length ? ('  (DUPLICATE codes w/ diff price: ' + [...new Set(dupes)].join(', ')) : '') + ')');
